services:
  web:
    build: .
    container_name: nextjs_template
    ports:
      - "3000:3000"
    env_file:
      - .env.test
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo_db_template
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: template
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
