import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar/Navbar';
import Providers from './context/providers';
import TodoContextProvider from './context/TodoContext';
import UsersContextProvider from './context/UserContext';
import AutoLogoutWatcher from './AutoLogoutWatcher';
import ClientWrapper from './components/ClientWrapper/ClientWrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 dark:bg-gray-800`}
      >
        <Providers>
          <UsersContextProvider>
            <TodoContextProvider>
              <Navbar />
              <ClientWrapper>{children}</ClientWrapper>
            </TodoContextProvider>
          </UsersContextProvider>
        </Providers>
      </body>
    </html>
  );
}
